/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { SourceNestedInput } from './SourceNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class PrimaryListenerCreateInput {
  @Field(() => String)
  public url: string;

  @Field(() => SourceNestedInput)
  public source: SourceNestedInput;

  // <keep-methods>
  // </keep-methods>
}
