/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { PrimaryListenerNestedInput } from './PrimaryListenerNestedInput';

// <keep-imports>
import { FetchRequest } from '../../services/fetch-request';
// </keep-imports>

@InputType()
export class SourceCreateInput {
  @Field(() => Number)
  public intervalSeconds: number;

  @Field(() => String)
  public url: string;

  @Field(() => PrimaryListenerNestedInput, { nullable: true })
  public primaryListener?: PrimaryListenerNestedInput | null;

  // <keep-methods>
  @Field(() => FetchRequest, { nullable: true })
  public config?: FetchRequest;
  // </keep-methods>
}
