/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import * as cleanDeep from 'clean-deep';
import { Arg, Args, Ctx, FieldResolver, ID, Info, Int, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../utils/add-eager-flags';
import * as auth from '../../utils/auth/auth-checkers';
import { getFindOptions } from '../../utils/get-find-options';
import { resolveGetters } from '../../utils/resolve-getters';
import { EntityId, EntityIdScalar } from '../EntityId';
import { PrimaryListenerCreateInput } from '../inputs/PrimaryListenerCreateInput';
import { PrimaryListenerEditInput } from '../inputs/PrimaryListenerEditInput';
import { PrimaryListenerSearchInput } from '../inputs/PrimaryListenerSearchInput';
import { PrimaryListenerSearchOrderInput } from '../inputs/PrimaryListenerSearchOrderInput';
import { IRequestContext } from '../IRequestContext';
import { PrimaryListener } from '../models/PrimaryListener';
import { PaginatedResponse } from '../PaginationResponse';

// <keep-imports>
// </keep-imports>

const PaginatedPrimaryListenerResponse = PaginatedResponse(PrimaryListener);

@Resolver(PrimaryListener)
export class PrimaryListenerCrudResolver {
  @Query(() => PrimaryListener)
  public async primaryListener(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(PrimaryListener, id, getFindOptions(PrimaryListener, info)));
  }

  @Query(() => PaginatedPrimaryListenerResponse)
  public async searchPrimaryListeners(
    @Arg('search', () => PrimaryListenerSearchInput, { nullable: true }) search: PrimaryListenerSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip: number = 0,
    @Arg('take', () => Int, { nullable: true }) take: number = 25,
    @Arg('order', () => [PrimaryListenerSearchOrderInput], { nullable: true }) order: Array<PrimaryListenerSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(PrimaryListener, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = addEagerFlags(await ctx.em.findAndCount(PrimaryListener, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    })));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [PrimaryListener])
  public async primaryListeners(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(PrimaryListener, getFindOptions(PrimaryListener, info)));
  }

  @Mutation(() => PrimaryListener)
  public async createPrimaryListener(@Arg('input') input: PrimaryListenerCreateInput, @Ctx() ctx: IRequestContext): Promise<PrimaryListener> {
    const model = new PrimaryListener();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => PrimaryListener)
  public async updatePrimaryListener(@Arg('input') input: PrimaryListenerEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(PrimaryListener, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  public async deletePrimaryListeners(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(PrimaryListener, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
