/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import * as cleanDeep from 'clean-deep';
import { Arg, Args, Ctx, FieldResolver, ID, Info, Int, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../utils/add-eager-flags';
import * as auth from '../../utils/auth/auth-checkers';
import { getFindOptions } from '../../utils/get-find-options';
import { resolveGetters } from '../../utils/resolve-getters';
import { EntityId, EntityIdScalar } from '../EntityId';
import { SourceCreateInput } from '../inputs/SourceCreateInput';
import { SourceEditInput } from '../inputs/SourceEditInput';
import { SourceSearchInput } from '../inputs/SourceSearchInput';
import { SourceSearchOrderInput } from '../inputs/SourceSearchOrderInput';
import { IRequestContext } from '../IRequestContext';
import { Source } from '../models/Source';
import { PaginatedResponse } from '../PaginationResponse';

// <keep-imports>
// </keep-imports>

const PaginatedSourceResponse = PaginatedResponse(Source);

@Resolver(Source)
export class SourceCrudResolver {
  @Query(() => Source)
  public async source(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(Source, id, getFindOptions(Source, info)));
  }

  @Query(() => PaginatedSourceResponse)
  public async searchSources(
    @Arg('search', () => SourceSearchInput, { nullable: true }) search: SourceSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip: number = 0,
    @Arg('take', () => Int, { nullable: true }) take: number = 25,
    @Arg('order', () => [SourceSearchOrderInput], { nullable: true }) order: Array<SourceSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Source, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = addEagerFlags(await ctx.em.findAndCount(Source, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    })));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Source])
  public async sources(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(Source, getFindOptions(Source, info)));
  }

  @Mutation(() => Source)
  public async createSource(@Arg('input') input: SourceCreateInput, @Ctx() ctx: IRequestContext): Promise<Source> {
    const model = new Source();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Source)
  public async updateSource(@Arg('input') input: SourceEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Source, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  public async deleteSources(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Source, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
