/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

import { Source } from './Source';

import { asPromise } from '../../utils/as-promise';
import * as auth from '../../utils/auth/auth-checkers';
import { IAuthorizable } from '../../utils/auth/IAuthorizable';
import { getInputOperationType } from '../../utils/get-input-operation-type';
import { noChange } from '../../utils/no-change';
import { SecondaryListenerAuth } from '../auth/SecondaryListenerAuth';
import { EntityId, EntityIdScalar } from '../EntityId';
import { SecondaryListenerCreateInput } from '../inputs/SecondaryListenerCreateInput';
import { SecondaryListenerEditInput } from '../inputs/SecondaryListenerEditInput';
import { SecondaryListenerNestedInput } from '../inputs/SecondaryListenerNestedInput';
import { IRequestContext } from '../IRequestContext';
import { updateSourceRelation } from './update-operations/secondaryListener-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class SecondaryListener implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new SecondaryListenerAuth(this);

  @Field(() => String)
  @Column({type: 'text',
    // <custom-column-args>
    // </custom-column-args>
  })
  public url: string;

  @Column({nullable: true, type: 'text',
    // <custom-column-args>
    // </custom-column-args>
  })
  public requestConfig?: string | null;

  @ManyToOne(() => Source, (source) => source.secondaryListeners , { nullable: true, onDelete: 'SET NULL' })
  @Field(() => Source , { nullable: true })
  public source: Promise<Source | undefined | null>;

  @CreateDateColumn()
  @Field()
  public createdAt: Date;

  @UpdateDateColumn()
  @Field()
  public updatedAt: Date;

  public async update(input: SecondaryListenerCreateInput | SecondaryListenerEditInput | SecondaryListenerNestedInput, context: IRequestContext) {
    const { source, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateSourceRelation(this, source, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
